import fs from "node:fs/promises";
import path from "node:path";
import type {
  GeneratedComponent,
  GeneratedHook,
  GeneratedTest,
  PipelineOutput,
  PipelineContext,
} from "../types/index.js";
import { logger } from "../observability/logger.js";

/**
 * Writes the pipeline output (components, hooks, tests, index) to disk
 * under the configured `outputDir`.
 */
export class OutputWriter {
  async write(
    components: GeneratedComponent[],
    hooks: GeneratedHook[],
    tests: GeneratedTest[],
    ctx: PipelineContext
  ): Promise<PipelineOutput> {
    const outputDir = path.resolve(ctx.outputDir);
    await this.ensureDirectories(outputDir);

    await Promise.all([
      ...components.map((c) => this.writeFile(c.path, c.code)),
      ...hooks.map((h) => this.writeFile(h.path, h.code)),
      ...tests.map((t) => this.writeFile(t.path, t.code)),
    ]);

    const indexContent = this.buildIndex(components, hooks, ctx);
    const indexPath = path.join(outputDir, "index.ts");
    await this.writeFile(indexPath, indexContent);

    logger.info("Output written", {
      outputDir,
      components: components.length,
      hooks: hooks.length,
      tests: tests.length,
    });

    return {
      featureName: ctx.featureName,
      outputDir,
      components,
      hooks,
      tests,
      indexFile: indexPath,
      externalDependencies: [],
    };
  }

  private async ensureDirectories(outputDir: string): Promise<void> {
    await Promise.all([
      fs.mkdir(path.join(outputDir, "components"), { recursive: true }),
      fs.mkdir(path.join(outputDir, "hooks"), { recursive: true }),
      fs.mkdir(path.join(outputDir, "tests"), { recursive: true }),
    ]);
  }

  private async writeFile(filePath: string, content: string): Promise<void> {
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, "utf-8");
    logger.debug("Wrote file", { path: filePath });
  }

  private buildIndex(
    components: GeneratedComponent[],
    hooks: GeneratedHook[],
    ctx: PipelineContext
  ): string {
    const componentExports = components
      .map((c) => {
        const relativeName = path.basename(c.path, ".tsx");
        return `export * from "./components/${relativeName}.js";`;
      })
      .join("\n");

    const hookExports = hooks
      .map((h) => {
        const relativeName = path.basename(h.path, ".ts");
        return `export * from "./hooks/${relativeName}.js";`;
      })
      .join("\n");

    return `/**
 * ${ctx.featureName} — auto-generated by frontend-pipeline
 * @generated
 */

${componentExports}
${hookExports ? "\n" + hookExports : ""}
`.trimEnd() + "\n";
  }
}
